markdown: redcarpet
pygments: true
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
title : "IBS 796: Basic Programming for Bioinformatics"
baseurl: http://bxlab.github.io/class-ibs-796-fall2013/
#production_url : 
#description: 
#disqus_shortname: caarlos0blog
#analytics: UA-32899481-1
#gauges: 50f2b533613f5d7c8000000c
author :
  name : James Taylor
  github : jxtx
  twitter : jxtx
  email: james@jamestaylor.org
